apiVersion: apps/v1
kind: Deployment
metadata:
  name: al7/ci-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: al7/ci-jenkins
  template:
    metadata:
      labels:
        app: al7/ci-jenkins
    spec:
      containers:
      - name: main-app
        image: 877009927021.dkr.ecr.ap-northeast-2.amazonaws.com/al7/ci-jenkins:v6
        ports:
        - containerPort: 8080
