apiVersion: argoproj.io/v1alpha1 # 1. API 버전 변경
kind: Rollout                   # 2. 객체 타입 변경
metadata:
  name: alive-deployment
  namespace: default
  labels:
    app: alive-app
spec:
  replicas: 4                   # Canary를 눈으로 확인하려면 리플리카 수가 좀 있는 게 좋습니다.
  selector:
    matchLabels:
      app: alive-app
  template:
    metadata:
      labels:
        app: alive-app
    spec:
      imagePullSecrets:
      - name: ecr-registry-key
      containers:
      - name: backend-container
        image: 877009927021.dkr.ecr.ap-northeast-2.amazonaws.com/al7/ci-jenkins:v6
        ports:
        - containerPort: 8080
  strategy:                     # 3. Canary 전략 추가
    canary:
      steps:
      - setWeight: 25           # 첫 번째 단계: 25% 트래픽 배정 (Pod 4개 중 1개만 신버전)
      - pause: {duration: 30s}  # 30초 동안 대기하며 상태 확인
      - setWeight: 50           # 두 번째 단계: 50%까지 확대
      - pause: {}               # 무기한 대기 (ArgoCD에서 직접 'Resume' 눌러야 최종 배포)
