apiVersion: apps/v1
kind: Deployment
metadata:
  name: alive-order-post-deployment
  namespace: backend
  labels:
    app: alive-order-post
spec:
  replicas: 3   # 주문 API보다 적게 시작
  selector:
    matchLabels:
      app: alive-order-post
  template:
    metadata:
      labels:
        app: alive-order-post
    spec:
      serviceAccountName: backend-secrets-sa
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: alive-order-post

      containers:
      - name: backend-container
        image: 877009927021.dkr.ecr.ap-northeast-2.amazonaws.com/al7/ci-jenkins:v75
        imagePullPolicy: Always

        env:
        - name: SPRING_PROFILES_ACTIVE
          value: order-post   # 🔥 핵심

        # (👇 아래는 전부 기존이랑 동일)
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: valkey-auth-sync
              key: password

        - name: MASTER_HOST
          valueFrom:
            secretKeyRef:
              name: db-auth-sync
              key: MASTER_HOST
        - name: SLAVE_HOST
          valueFrom:
            secretKeyRef:
              name: db-auth-sync
              key: SLAVE_HOST
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: db-auth-sync
              key: PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-auth-sync
              key: DB_NAME
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: db-auth-sync
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-auth-sync
              key: PASSWORD
        - name: ORDER_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: db-auth-sync
              key: ORDER_QUEUE_URL
        - name: DD_SERVICE
          value: "alive-order-post"
        - name: DD_ENV
          value: "prod"
        - name: DD_VERSION
          value: "v61"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "8126"
        - name: DD_LOGS_INJECTION
          value: "true"

        #  # sqs
        # - name: order-queue-url
        #   valueFrom:
        #     secretKeyRef:
        #       name: sqs-auth-sync
        #       key: order-queue-url

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"

        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets"
          readOnly: true

      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "alive-valkey-spc"

      imagePullSecrets:
      - name: ecr-registry-key
