apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets      # Deployment에서 참조할 이름
  namespace: backend          # Deployment와 같은 namespace
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "alive/test/secret"   # AWS Secrets Manager Secret 이름
        objectType: "secretsmanager"
        objectAlias: "db-secret"        # Pod에서 마운트될 파일 이름
