apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: alive-valkey-spc
  namespace: backend
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "valkey-endpoint-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "CACHE_ENDPOINT"
            objectAlias: "VALKEY_ENDPOINT"

      - objectName: "db-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: MASTER_HOST
            objectAlias: MASTER_HOST
          - path: SLAVE_HOST
            objectAlias: SLAVE_HOST
          - path: PORT
            objectAlias: PORT
          - path: DB_NAME
            objectAlias: DB_NAME
          - path: USERNAME
            objectAlias: USERNAME
          - path: PASSWORD
            objectAlias: PASSWORD
          - path: ORDER_QUEUE_URL
            objectAlias: ORDER_QUEUE_URL


  secretObjects:
    # Valkey Secret
    - secretName: valkey-endpoint-sync
      type: Opaque
      data:
        - objectName: VALKEY_ENDPOINT
          key: valkey_endpoint

    # DB Secret
    - secretName: db-auth-sync
      type: Opaque
      data:
        - objectName: MASTER_HOST
          key: MASTER_HOST
        - objectName: SLAVE_HOST
          key: SLAVE_HOST
        - objectName: PORT
          key: PORT
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: USERNAME
          key: USERNAME
        - objectName: PASSWORD
          key: PASSWORD
        - objectName: ORDER_QUEUE_URL
          key: ORDER_QUEUE_URL
    
    # # SQS Secret
    # - secretName: sqs-auth-sync
    #   type: Opaque
    #   data:
    #     - objectName: order-queue-url
    #       key: order-queue-url
  refreshInterval: 1m  # ← 여기서 자동 갱신 주기 설정
