apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: alive-valkey-spc
  namespace: backend
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "valkey_key"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: valkey_password

      - objectName: "db-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: MASTER_HOST
            objectAlias: MASTER_HOST
          - path: SLAVE_HOST
            objectAlias: SLAVE_HOST
          - path: PORT
            objectAlias: PORT
          - path: DB_NAME
            objectAlias: DB_NAME
          - path: USERNAME
            objectAlias: USERNAME
          - path: PASSWORD
            objectAlias: PASSWORD
          - path: order-queue-url
            objectAlias: order-queue-url


  secretObjects:
    # Valkey Secret
    - secretName: valkey-auth-sync
      type: Opaque
      data:
        - objectName: valkey_password
          key: password

    # DB Secret
    - secretName: db-auth-sync
      type: Opaque
      data:
        - objectName: MASTER_HOST
          key: MASTER_HOST
        - objectName: SLAVE_HOST
          key: SLAVE_HOST
        - objectName: PORT
          key: PORT
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: USERNAME
          key: USERNAME
        - objectName: PASSWORD
          key: PASSWORD
        - objectName: order-queue-url
          key: order-queue-url
    
    # # SQS Secret
    # - secretName: sqs-auth-sync
    #   type: Opaque
    #   data:
    #     - objectName: order-queue-url
    #       key: order-queue-url
