apiVersion: v1
kind: Service
metadata:
  name: sonarqube-db
  namespace: sonarqube
spec:
  ports:
    - port: 5432
  selector:
    app: sonarqube-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-db
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-db
  template:
    metadata:
      labels:
        app: sonarqube-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: sonar
            - name: POSTGRES_PASSWORD
              value: sonar
            - name: POSTGRES_DB
              value: sonar
          ports:
            - containerPort: 5432
