apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alive-apps-pdb      # PDB의 이름 (자유롭게 지정)
  namespace: backend    # 대상 앱이 배포된 네임스페이스
spec:
  minAvailable: 50%     
  selector:
    matchLabels:
      app: alive-app # 중요: 대상 Deployment의 template.metadata.labels와 일치해야 함

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alive-apps-pdb      # PDB의 이름 (자유롭게 지정)
  namespace: backend    # 대상 앱이 배포된 네임스페이스
spec:
  minAvailable: 50% 
  selector:
    matchLabels:
      app: alive-order-post # 중요: 대상 Deployment의 template.metadata.labels와 일치해야 함
